version: "3"
services:

  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  wordpress:
    image: wordpress:4.9
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./gik-theme:/var/www/html/wp-content/themes/gik
